### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by GrosSacASac**

### CODE REVIEW

**Comment by GrosSacASac** [comment]
We can continue here

**Comment by ShishirPatil** [comment]
@GrosSacASac Thanks for this and sorry for the delay. 
I was wondering if you got a chance to test this? I have a Dual shock 4 that I tested with, and it seemed to work fine. I'll try to see if I can get access to a Xbox controller and test it too.

**Comment by GrosSacASac** [comment]
Yes I tested with a Xbox one controller

**Comment by GrosSacASac** [comment]
Nice.
You could enable issues in the settings

**Pull request merged**
